server:
  port: 9090
spring:
  application:
    name: GSS-gateway
  #gateway配置
  cloud:
    alibaba:
      seata:
        txServiceGroup: my_test_tx_group #配置事务分组
    gateway:
      routes: #路由规则
        - id: user_route
          uri: lb://GSS-User #需要转发的地址 lb就是使用nacos本地负载均衡策略
          predicates: #断言规则 用于路由规则的匹配
            - Path=/user/**
        - id: goods_route
          uri: lb://GSS-Goods
          predicates:
            - Path=/goods/**
        - id: recharge_route
          uri: lb://GSS-Recharge
          predicates:
            - Path=/alipay/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]': #拦截的请求
            allowedOrigins: #允许跨域的请求
              - "http://localhost:3000"
              - "http://127.0.0.1:3000"
            allowedMethods: #运行跨域的请求方式
              - "GET"
              - "POST"
            allowedHeaders: "*" #允许请求中携带的头信息
            allowedCredentials: true #是否允许携带cookie
            maxAge: 36000 #跨域检测的有效期,单位s
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: public
        ephemeral: true

          #scg:
        #fallback:
        #mode: response
        #response-body: "{code:'',message:''}"
seata:
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848 #seata所在的nacos地址
      application: seata-server #seata的服务名
      username: nacos
      password: nacos
      group: SEATA_GROUP #seata所在的组
  config: #配置seata的配置中心 可以读取一些关于seata client的一些配置
    type: nacos
    nacos:
      serverAddr: localhost:8848 #seata所在的nacos地址
      application: seata-server #seata的服务名
      username: nacos
      password: nacos
      group: SEATA_GROUP #seata所在的组